---
title: "Forecast" 
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document 
vignette: >
  %\VignetteIndexEntry{Forecast}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
suppressMessages(library(viridis))
suppressMessages(library(ramp.work))
#devtools::load_all()
```

We set up a model with inter-annual variability over a five-year period:

```{r}
mod1 <- xds_setup_cohort(
  eir = 2/365,
  season_par = makepar_F_sin(bottom=.1),
  trend_par = makepar_F_spline(tt=365*(0:5), yy=c(.7, 2, 1.5, .9, .7, 1.5))
)
tt <- seq(0, 365*5, by = 30)
mod1 <- xds_solve_cohort(mod1, times=tt)
mod1 <- last_to_inits(mod1)
mod1 <- xds_solve_cohort(mod1, times=tt)
xds_plot_PR(mod1)
```

If we run the model for the next five years, we get a runaway trend. 

```{r}
tt <- seq(0, 365*10, by = 30)
mod1 <- xds_solve_cohort(mod1, times=tt)
xds_plot_PR(mod1)
```

If we want to use the model to forecast a few years ahead, we need to add knots. The functions `forecast_spline_EIR` and `forecast_spline_Lambda` do this for $N$ years ahead. 

```{r}
mod1a <- forecast_spline_EIR(mod1, 5)
mod1a <- xds_solve_cohort(mod1a, times=tt)
clrs <- viridis::turbo(8)
xds_plot_PR(mod1a)
for(i in 1:8){
  mod1b <- forecast_spline_EIR(mod1, 5)
  mod1b <- xds_solve_cohort(mod1b, times=tt)
  xds_plot_PR(mod1b, add=TRUE, clrs = clrs[i])
}

xds_plot_PR(mod1a, add=TRUE, clrs = "black")
segments(5*365, 0, 5*365, 1, lty = 2)
```
```{r}
mod1c <- forecast_spline_EIR(mod1, 15)
tt <- seq(0, 365*20, by = 30)
mod1c <- xds_solve_cohort(mod1c, times=tt)
xds_plot_PR(mod1c)
segments(5*365, 0, 5*365, 1, lty = 2)
```
