---
title: "Burn-in for Fitting" 
subtitle: "Setting Initial Values through Hindcasting" 
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document 
vignette: >
  %\VignetteIndexEntry{Burn-in for Fitting}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

***

*A challenge for fitting dynamical systems to data is how to set the initial conditions. **`ramp.work`** handles this with an algorithm called `hindcast_ty`*

***

Suppose we have a set of *Pf*PR values, $x_i,$ observed at time points $t_i,$  and suppose we want to fit a model to output predicted values of *Pf*PR at those time points, $\hat x_i.$ There are functions in **`ramp.work`** to fit dynamical systems to data, but doing this well requires understanding how dynamical systems are set up and solved. 

In these systems, infection and immunity are represented by a set of states, $X,$ and the system is defined by a dynamical system, $dX/dt.$ In **`ramp.xds`** each malaria model defines an observational process to output *Pf*PR: $F_x(X) = x.$ To solve the equation, we must set the initial values for the variables, denoted $X_0,$ and output $X(t)$. If we ask the solver to output $X(t_i),$ then we compute $\hat x_i = F_x(X(t_i)).$

A challenge for using dynamical systems is that the predicted values for some values of $\hat x_i(t_i)$ could change, depending on how we set the initial values for the state variables and burn-in. There are several ways of handling it. We could initialize the model at some point in the remote past, but we don't know what happened *before* the study began? We will need to handle this in some way. We set up a hindcast and then set the initial conditions through a process we call *burn-in.* 

To get consistent results from our model fitting, we need to have a well-defined, consistent method for setting up forcing in the *pre-observation* period to handle burn-in. The algorithm we have developed for splines is called `hindcast_ty.` This vignette describes how to configure hindcasting, with two examples.  

```
model <- hindcast(model, N, method, impute_ty, trusted_ty)
``` 

+ `model` is a **`ramp.xds`** model object

+ `N` is the number of interpolation points in the hindcast, one for each past year 

+ `method` describes how to set the value of the hindcasted interpolation points: 

    - `class(method) = "value"` -- Set the $y$ value for all hindcasted interpolation points to a single value. 
    
    - `class(method) = "mirror"` -- Use the $y$ values for the fitted interpolation points in reverse to set $y$ values for the hindcasted enterpolation points. 

+ `impute_ty` and `trusted_ty` set up imputation

As an aside, this is not *just* a model fitting problem: malaria epidemiology has a *memory* problem -- immunity is a function of cumulative exposure, so most quantities in malaria will depend on the past. The *burn-in* gives us something like an imputed *in silico* population. 


## Default

By default, `hindcast` sets up $N=10$ years of pre-observation interpolation points. The pre-observation $y$ values are set to the first fitted interpolation point $y_0$. 

This rule is enforced through a fitting process; every time the fitted values change, the function `impute_ty` is called to update the interpolation points for the hindcasting period. 

```
method = "value"
impute_ty = "first"
trusted_ty = "first"
```


## Mirror 

In the second algorithm, we reverse the order of the fitted interpolation points.  

```
method = "mirror"
impute_ty = "reverse"
trusted_ty = "all"
```

## Implementation Notes 

The default hindcasting algorithm is set up as part of `setup_fitting` with $N=10.$ To change the options, run `setup_hindcast` with new options after


