---
title: "Test Fit"
output: html_document
---

```{r}
library(ramp.xds)
library(ramp.library)
library(ramp.control)
#library(ramp.uganda)
devtools::load_all("~/git/ramp.uganda")
```



## Working Directory

```{r}
save_to = "/Users/smitdave/git/ramp.work/vignettes/"
save_as <- "sis_si.rds" 
file_name <- paste(save_to, save_as, sep="")
sis_si_base <- readRDS(file_name)
```

```{r prts}
i = 132
prts <- get_district_pfpr_i(i)
district_name <- prts$district_name[1]
```

```{r}
Sp<- makepar_F_sin(bottom=1, phase=180) 
sis_si_base$Lpar[[1]]$season_par <- Sp 
sis_si_base$Lpar[[1]]$F_season <- make_function(Sp)
```

```{r, echo=F}
devtools::load_all()
```



```{r}
fit_mod <- setup_fitting(sis_si_base, prts$pfpr, prts$jdate)
```



```{r, eval=F}
fit_mod <- pr2history(prts$pfpr, prts$jdate, fit_mod)
```
```{r, eval=F}
file_name <- paste(save_to, "fit_mod.rds", sep="")
saveRDS(fit_mod, file_name)
```

```{r}
file_name <- paste(save_to, "fit_mod.rds", sep="")
fit_mod <- readRDS(file_name)
```

```{r}
fit_mod <- xds_solve(fit_mod, times = prts$jdate)
profile_pr(fit_mod, prts)
```


```{r}
irs_history <- make_irs_history(district_name)
bednet_history <- make_bednet_history(district_name)
```

```{r, echo=F}
devtools::load_all()
```

```{r}
recon <- reconstruct_baseline(fit_mod, prts$pfpr, prts$jdate, irs_history, bednet_history)
```

