---
title: "Forecasting" 
subtitle: "Implementing a Forecast" 
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document 
vignette: >
  %\VignetteIndexEntry{Forecasting}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo=FALSE}
sip_si <- readRDS("evaluate.rds")
```


```{r}
clrs = viridisLite::turbo(5)
sip_si_f1 <- change_forecast_ix(sip_si, c(2,3,5), 12, "subsamp")
show_trend(sip_si_f1, seq(0, 20*365, 15), clr = "darkred")
for(i in 1:5){
  sip_si_fi <- change_forecast_ix(sip_si, c(2,3,5), 12, "subsamp")
  show_trend(sip_si_fi, seq(0, 20*365, 15), clr = clrs[i], add=T)
}
segments(3650, 0, 3650, 1.7, col = grey(0.5))
show_trend(sip_si, seq(0, 20*365, 15), add=T)
```
```{r}
tt = 3650 + 365*c(1:12)
yy = exp(-.03*c(0:11))
sip_si_d1 <- change_forecast_ty(sip_si, tt, yy) 
yy = exp(.03*c(0:11))
sip_si_d2 <- change_forecast_ty(sip_si, tt, yy) 
show_trend(sip_si_d2, seq(0, 20*365, 15), clr = "darkred")
show_trend(sip_si_d1, seq(0, 20*365, 15), clr = "darkblue", add=T)
segments(3650, 0, 3650, 1.7, col = grey(0.5))
show_trend(sip_si, seq(0, 20*365, 15), add=T)
```
