
#' @title Add a "forecast"
#' @description
#' Use the nodes of a trend function, defined as a spline, to
#' "forecast" the future by sub-sampling from the knots
#' @param spline_par parameters to set up a spline function
#' @param N the number of years ahead to forecast
#' @param x_last the number of last knot points to exclude
#' @export
forecast_spline= function(spline_par, N=5, x_last=0){
  # Time points
  tt <- spline_par$tt
  tt_new = max(tt) + 365*c(1:(N+2))
  spline_par$tt = c(tt, tt_new)
  # Knot values
  yy <- spline_par$yy
  if(x_last>0){
    ll = length(yy) - x_last
    yy = yy[1:ll]
    N = N+x_last
  }
  #yy_new <- sample(yy, N+2, replace=TRUE)
  yy_new <- gam_sample(yy, N+2)
  spline_par$yy = c(yy, yy_new)
  return(spline_par)
}

#' @title Sample from a fitted gamma
#' @description
#' Use the nodes of a trend function, defined as a spline, to
#' "forecast" the future by sub-sampling from a fitted gamma
#' @param yy the knots
#' @param N the number of years ahead to forecast
#' @importFrom stats dgamma rgamma optimize
#' @export
gam_sample <- function(yy, N){
  gam_lik <- function(shp, yy){
    -sum(log(dgamma(yy, shp, shp)))
  }
  optimize(gam_lik, c(0, 10), yy=yy)$min -> shape
  rgamma(N, shape, shape)
}

#' @title Add a "forecast"
#' @description
#' Use the nodes of a trend function, defined as a spline, to
#' "forecast" the future by sub-sampling from the knots
#' @param model a list that defines an `ramp.xds` model (*e.g.*,  generated by `xde_setup()`)
#' @param N the number of years ahead to forecast
#' @param x_last the number of last knot points to exclude
#' @export
forecast_spline_EIR = function(model, N=5, x_last=0){
  model$EIRpar$trend_par <- forecast_spline(model$EIRpar$trend_par, N, x_last)
  model$EIRpar$F_trend <- make_function(model$EIRpar$trend_par)
  return(model)
}

#' @title Add a "forecast"
#' @description
#' Use the nodes of a trend function, defined as a spline, to
#' "forecast" the future by sub-sampling from the knots
#' @param model a list that defines an `ramp.xds` model (*e.g.*,  generated by `xde_setup()`)
#' @param N the number of years ahead to forecast
#' @param s the species to forecast
#' @param x_last the number of last knot points to exclude
#' @export
forecast_spline_Lambda = function(model, N=5, s=1, x_last=0){
  model$Lpar[[s]]$trend_par <- forecast_spline(model$Lpar[[s]]$trend_par, N, x_last)
  model$Lpar[[s]]$F_trend <- make_function(model$Lpar[[s]]$trend_par)
  return(model)
}
